In [15]:
import numpy as np
import random
import pandas as pd

In [2]:
n = 50000
num_ads = 9
zero_transition_to_one_prob = [0.3,0.1,0.4,0.2,0.23,0.17,0.26,0.12,0.25]  #fixing values here for reproducibility
one_transition_to_one_prob = [0.2,0.16,0.23,0.3,0.08,0.13,0.15,0.17,0.21] #fixing values here for reproducibility

In [3]:
data = np.zeros((n,num_ads))

In [5]:
print(data.shape)

(50000, 9)


In [6]:
data[0] = [0,0,0,0,1,0,0,0,0] #fixing values here for reproducibility

In [10]:
for i in range(1,n):
    for j in range(num_ads):
        prev_val = data[i-1,j]
        rand_val = random.random()
        if prev_val == 0:
            threshold = zero_transition_to_one_prob[j]
            if rand_val < threshold:
                data[i,j] = 1
            else:
                data[i,j] = 0
        else:
            threshold = one_transition_to_one_prob[j]
            if rand_val < threshold:
                data[i,j] = 1
            else:
                data[i,j] = 0
            

In [13]:
print(data[:5])

[[0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0.]]


In [17]:
result = pd.DataFrame(data)

In [19]:
result.to_csv("data.csv",index = False)